### ISSUE TITLE
Minimum bandwidth

### ISSUE THREAD

**Issue by alexwireless** [analogdevicesinc/TransceiverToolbox#102]
Hi

I am wondering why Pluto has a minimum bandwidth? a maximum is justified by the hardware capabilities, but what constrains the minimum??

**Comment by tfcollins** [comment]
The minimum is data rate is 65104.1666667 SPS with the FPGA dec/int filters. 520833.333333 SPS with the transceiver alone. The clocks stop functioning at lower rates across temperature.

This comes from the minimum ADC rate of 25 MSPS / Max decimation of 48 / Decimation in FPGA (8).
