### ISSUE TITLE
Content not supported for Matlab R2018a

### ISSUE THREAD

**Issue by dsp-payloads** [analogdevicesinc/TransceiverToolbox#11]
Fails to install v19.2.1 of the toolbox in Matlab R2018a

**Comment by tfcollins** [comment]
Yes as the release notes say v19.2.1 is for R2019b.

You can try an earlier release, or go back to the older MathWork_tools repo: https://github.com/analogdevicesinc/MathWorks_tools/releases

-Travis

**Comment by tfcollins** [comment]
Closing for now. Reopen if this is still an issue.

-Travis
