### ISSUE TITLE
SD card image for ADRV9009 + ZCU102 for Toolbox support

### ISSUE THREAD

**Issue by axdy** [analogdevicesinc/TransceiverToolbox#111]
Documentation indicates that custom HDL IP can be deployed and interfaces through MATLAB/Simulink. When I run the 'Embedded System Integration -> Program Device' I receive a ``STDERR: bash: mw_setboot: command not found`` indicating that a MATLAB compatible SD card image is needed for my board to communicate with it.

Where can I find this? The [doc](https://analogdevicesinc.github.io/TransceiverToolbox/master/) mentions no SD card image.

Thanks,
Andrew

**Comment by Axdy** [comment]
![image](https://user-images.githubusercontent.com/24210638/173421247-b333a31d-22b0-4abb-b4b1-f747a320e5c6.png)

**Comment by tfcollins** [comment]
This hasn't made it over to the new markdown doc but the basic idea is you need to create a BOOT.BIN. This is done automatically for you with a provided TCL script. See this older doc page which still applies: https://wiki.analog.com/resources/tools-software/transceiver-toolbox#hdl_targeting_with_hdl-coder

**Comment by Axdy** [comment]
Found it thanks. Ended up using the .elf files that are written into the 'bootgen_sys.gz' file on the Kuiper SD card along with my own bitstream. .elf files I found on the repository and the ones created in 2019.1 Vivado SDK did not boot properly.
