### ISSUE TITLE
Update for MATLAB/Simulink 2022a and Vivado 2022.1

### ISSUE THREAD

**Issue by warnes** [analogdevicesinc/TransceiverToolbox#113]
Please (help me) update Tranciever Toolbox for use with the current versions of MATLAB/Simulink (2022a) and Vivado (2022.1).

**Comment by tfcollins** [comment]
The current 2021b release should work fine with 2022a. However, our HDL support is dependent on the ADI HDL repo which is based on Vivado 2019.1 and will support 2021.1 soon. Upgrading to newer versions are usually very error prone.

**Comment by warnes** [comment]
Ok, thanks, I’ll install Vivado 2019.1.
