### ISSUE TITLE
HDL targetting for Pluto SDR

### ISSUE THREAD

**Issue by warnes** [analogdevicesinc/TransceiverToolbox#114]
What is necessary to enable HDL targeting for the Pluto SDR?

**Comment by tfcollins** [comment]
Pluto follows the same flow to generate bitstreams as the other supported platforms. However, to leverage the bitstreams you will need to build the generated HDF or BIT files into the firmware. See here for the firmware build process: https://wiki.analog.com/university/tools/pluto/building_the_image You will just replace the bitstream generated from the HDL repo with the one from HDL-Coder.

**Comment by warnes** [comment]
Ok, thanks!
