### ISSUE TITLE
Fix favicon to use doc one

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/TransceiverToolbox#124]

**Comment by rgetz** [comment]
https://github.com/analogdevicesinc/TransceiverToolbox/blob/gh-pages/master/assets/images/favicon.png just needs to be replaced.

**Comment by tfcollins** [comment]
Fixed https://github.com/analogdevicesinc/TransceiverToolbox/commit/641399b1ec1f16b224b89efaa0c1da4c99c57882
