### ISSUE TITLE
Is a hardware device required to use this toolbox?

### ISSUE THREAD

**Issue by AndyZe** [analogdevicesinc/TransceiverToolbox#184]
I'm a little confused about what this toolbox actually does. I'd like to simulate an ADRV9001 without having the hardware. Specifically, I'd like to get familiar with the API such as `adi_adrv9001_Rx_DecimatedPower_Get()` and how setting/getting the AGC structs works. Can this toolbox do that?

(Cross-posted here:
https://www.mathworks.com/matlabcentral/fileexchange/72645-analog-devices-inc-transceiver-toolbox?tab=discussions#discussions_2601856
)

**Comment by tfcollins** [comment]
Transceiver Toolbox is primarily a hardware support package which interfaces with kernel drivers and provides HDL targeting. It leverages such drivers as the one for ADRV9002 https://wiki.analog.com/resources/tools-software/linux-drivers/iio-transceiver/adrv9002 and other generations of transceivers

No models exist for the ADRV9002 family.

The raw API you reference has only information in the SDK and part userguide

**Comment by AndyZe** [comment]
Alright, thanks. Consider adding some high-level description of what this pkg does in the README.
