### ISSUE TITLE
LTETests fail too long when device not found

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/TransceiverToolbox#68]
Current test without hardware hooked up took 10 minutes to fail.

If a device is not found every enumerated test has to fail to stop the test. There should be a similar check done at startup like here: https://github.com/analogdevicesinc/TransceiverToolbox/blob/master/test/AD9361Tests.m#L10

**Comment by SrikanthPagadarai** [comment]
#69 has fixed this bug.
