### ISSUE TITLE
Problem with the Fast Frequency Hopping Example

### ISSUE THREAD

**Issue by sdrlab** [analogdevicesinc/TransceiverToolbox#78]
we have a question about Frequency Hopping Example of the RF SOM with Transceiver Toolbox
https://wiki.analog.com/resources/eval/user-guides/adrv936x_rfsom/tutorials/frequency_hopping

we followed the tutorial and finished all the steps include building kernel, and when we run the fastlock.m script in matlab we get an error says:
 **"Abstract classes cannot be instantiated.  Class 'FrequencyHopper' is declared as Abstract.'**
Since this is an error in the code, we assume we have no problem of missing libraries or wrong installation.
Can you give us an advice how to sort it?

Thank you

p.s
We are using matlab 2020b and vivado 2018.3 as said in the requirements, we also installed libio as said in the starting guide, and the required compiler. (We tried running it both on linux ubuntu 16.04 and windows 10, and received the same error).

**Comment by tfcollins** [comment]
Which release of the toolbox are you using?

**Comment by sdrlab** [comment]
We are using version 20.2.1
![image](https://user-images.githubusercontent.com/86557358/123586512-83991200-d7ed-11eb-8766-21b611fe30d9.png)

**Comment by tfcollins** [comment]
This was fixed here: https://github.com/analogdevicesinc/TransceiverToolbox/commit/90db749365b73dd50d67da07aecd600bb93d985c

I've update the MLTBX file on the github release page. Either grab the FrequencyHopper.m file directly or re-install the toolbox.
