### ISSUE TITLE
Analog Devices Inc, Transceiver Toolbox Question about deployment

### ISSUE THREAD

**Issue by sdrlab** [analogdevicesinc/TransceiverToolbox#79]
Hello,

We have a question about the toolbox,  from our understanding the toolbox use libiio library which is written in c++/c and its main role is to create an easy interface to kernel commands to connect from host pc to the device and send commands to change the attributes and parameters of the transceiver.

We would like to know if beside the feature of using external mode (using a host pc to connect over network to the device), is there a way to use this toolbox for deployment on the ARM by using code generation from matlab? In other words, if we generate a Simulink model that uses the iio system object of the toolbox transceiver and generate matlab c code and compile it, will it be able to run on the ARM? If so, we would like to get instructions how to do it. If it is not the case, what is your recommendation on how to do it with c++.
If our scenario is not easy to understand, we use the HDL workflow advisor to generate FPGA code and copy the bit file that it generates to our device, but instead of writing the ARM code with the provided interface of Simulink, we want to write it ourselves in c++, but we do not know how to start.

Thanks a lot.

**Comment by tfcollins** [comment]
Answering the question on EZ: https://ez.analog.com/sw-interface-tools/f/q-a/546948/analog-devices-inc-transceiver-toolbox-question-about-deployment
