### ISSUE TITLE
What is the transceiver toolbox for matlab 2021b

### ISSUE THREAD

**Issue by alexwireless** [analogdevicesinc/TransceiverToolbox#97]
Hello. I am trying to open the AnalogDevicesTransceiverToolbox_v21.1.1.mltbx file in matlab 2021b. However, the following message appears: You are installing content that is not supported for this MATLAB release or for this platform. What shall I do?

**Comment by tfcollins** [comment]
We are working on a release specifically for R2021b but v21.1.1 has been tested and should work for R2021b.

-Travis
